# Generated by Django 5.2.10 on 2026-03-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
