# Generated by Django 5.2.9 on 2026-01-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogtag_comment_blog_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
